[2025-07-21T14:10:59.767+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509
[2025-07-21T14:10:59.767+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering'
[2025-07-21T14:10:59.783+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509
[2025-07-21T14:10:59.783+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering'
[2025-07-21T14:10:59.799+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: feature_engineering_dag.run_feature_engineering manual__2025-07-21T14:10:56.738625+00:00 [queued]>
[2025-07-21T14:10:59.803+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: feature_engineering_dag.run_feature_engineering manual__2025-07-21T14:10:56.738625+00:00 [queued]>
[2025-07-21T14:10:59.803+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-07-21T14:10:59.809+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_feature_engineering> on 2025-07-21 14:10:56.738625+00:00
[2025-07-21T14:10:59.811+0000] {standard_task_runner.py:57} INFO - Started process 70 to run task
[2025-07-21T14:10:59.814+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'feature_engineering_dag', 'run_feature_engineering', 'manual__2025-07-21T14:10:56.738625+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/feature_engineering.py', '--cfg-path', '/tmp/tmpimaog9fq']
[2025-07-21T14:10:59.815+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask run_feature_engineering
[2025-07-21T14:10:59.825+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-21T14:10:59.843+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509
[2025-07-21T14:10:59.843+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=feature_engineering_dag/run_id=manual__2025-07-21T14:10:56.738625+00:00/task_id=run_feature_engineering'
[2025-07-21T14:10:59.844+0000] {task_command.py:415} INFO - Running <TaskInstance: feature_engineering_dag.run_feature_engineering manual__2025-07-21T14:10:56.738625+00:00 [running]> on host 94007307d8a8
[2025-07-21T14:10:59.886+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='feature_engineering_dag' AIRFLOW_CTX_TASK_ID='run_feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-07-21T14:10:56.738625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-21T14:10:56.738625+00:00'
[2025-07-21T14:10:59.894+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-21T14:10:59.897+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/feature_engineering.py", line 19, in feature_engineering
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-21T14:10:59.911+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=feature_engineering_dag, task_id=run_feature_engineering, execution_date=20250721T141056, start_date=20250721T141059, end_date=20250721T141059
[2025-07-21T14:10:59.918+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task run_feature_engineering (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 70)
[2025-07-21T14:10:59.946+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-21T14:10:59.957+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
