[2025-07-20T21:15:37.943+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:15:37.945+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:15:37.960+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:15:37.960+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:15:37.979+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:15:36.018387+00:00 [queued]>
[2025-07-20T21:15:37.985+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:15:36.018387+00:00 [queued]>
[2025-07-20T21:15:37.986+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-20T21:15:37.993+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): aggregate_and_store_pickle_data> on 2025-07-20 21:15:36.018387+00:00
[2025-07-20T21:15:37.996+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2025-07-20T21:15:37.998+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_pipeline', 'aggregate_and_store_pickle_data', 'manual__2025-07-20T21:15:36.018387+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/fraud_pipeline_dag.py', '--cfg-path', '/tmp/tmpk26nskez']
[2025-07-20T21:15:38.000+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask aggregate_and_store_pickle_data
[2025-07-20T21:15:38.011+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-20T21:15:38.032+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:15:38.032+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:15:36.018387+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:15:38.034+0000] {task_command.py:415} INFO - Running <TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:15:36.018387+00:00 [running]> on host 9555ccf33d88
[2025-07-20T21:15:38.077+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_and_store_pickle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T21:15:36.018387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-20T21:15:36.018387+00:00'
[2025-07-20T21:16:21.088+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2025-07-20T21:16:21.256+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
